version: '3'
services:
  kamailio:
    build: .
    hostname: kamailio
    container_name: kamailio
    restart: always
    environment:
      - ADMIN_PASSWORD=admin123

    logging:
      options:
      max-size: 50m
    tty: true
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "5160:5160/tcp"
      - "18000-18100:18000-18100/udp"
    volumes:
      - ./kamailio:/usr/local/etc/kamailio
      - backup:/backup
      - recordings:/var/spool/asterisk/monitor
